from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('login', views.login),
    path('main', views.main),
    path('create_account' , views.create_account),
    path('create_account_form_handler', views.create_account_form_handler),
    path('username_validate', views.username_validate),
    path('account_recovery', views.account_recovery),
    path('account_recovery_email', views.account_recovery_email),
    path('account_recovery_inputcode', views.account_recovery_inputcode),
    path('account_recovery_code', views.account_recovery_code),
    path('account_recovery_final', views.account_recovery_final),
    path('reset_password', views.reset_password),
    path('logout', views.logout),
    path('settings', views.settings),
    path('edit_profile', views.edit_profile),
    path('editprofile_savechanges', views.editprofile_savechanges),
    path('profilepic_upload', views.profilepic_upload),
    path('profilepic_crop', views.profilepic_crop),
    path('profilepic_cropped_upload', views.profilepic_cropped_upload),
    path('display_profile/<str:uid>/', views.display_profile, name='uid'),
    path('personal_information', views.personal_information),
    path('change_email_modal', views.change_email_modal),
    path('change_email_modal_confirm', views.change_email_modal_confirm),
    path('change_password_modal', views.change_password_modal),
    path('change_password_modal_confirm', views.change_password_modal_confirm),
    path('friends', views.friends),
    path('your_friends', views.your_friends),
    path('ping', views.ping),
    path('add_friends', views.add_friends),
    path('add_friends_result', views.add_friends_result),
    path('profilepic_temp_upload', views.profilepic_temp_upload),
    path('send_friend_request', views.send_friend_request),
    path('pending_invites', views.pending_invites),
    path('cancel_decline_friend_request', views.cancel_decline_friend_request),
    path('accept_friend_request', views.accept_friend_request),
    path('main_online_friends', views.main_online_friends),
    path('matchmaking', views.matchmaking_page),
    path('pending_friends_notif', views.pending_friends_notif),
    path('manage_friend', views.manage_friend),
    path('remove_friend', views.remove_friend),
    path('matchmaking_onload', views.matchmaking_onload),
    path('matchmaking_cancel', views.matchmaking_cancel),
    path('check_joined_row', views.check_joined_row),
    path('check_match_created', views.check_match_created),
    path('match', views.match_page),
    path('match_animation_sequence', views.match_animation_sequence),
    path('get_match_info/<str:room_name>/<int:user_round>/', views.get_match_info),
    path('match_do_move', views.match_do_move),
    path('leave_match_modal', views.leave_match_modal),
    path('leave_match', views.leave_match),
    path('match_ping/<str:room_name>/', views.match_ping),
    path('invite_friend_modal', views.invite_friend_modal),
    path('invite_friend', views.invite_friend),
    path('check_invite_deny', views.check_invite_deny),
    path('check_match_invites', views.check_match_invites),
    path('accept_invite', views.accept_invite),
    path('decline_invite', views.decline_invite),
    path('leaderboard', views.leaderboard_page),
    path('load_leaderboard', views.load_leaderboard),
    path('delete_account_modal', views.delete_account_modal),
    path('delete_account_code_send', views.delete_account_code_send),
    path('delete_account_final_modal', views.delete_account_final_modal),
    path('delete_account', views.delete_account),
    path('about', views.about)
]
