# Generated by Django 5.1.4 on 2025-01-03 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=40)),
                ('joindate', models.CharField(default='0', max_length=64)),
                ('description', models.CharField(default='No description', max_length=300)),
                ('profile_picture', models.CharField(default='defaultprofile.jpg', max_length=128)),
            ],
        ),
    ]
