# Generated by Django 5.1.4 on 2025-01-04 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoemult', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stayloggedin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
