# Generated by Django 5.1.4 on 2025-01-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoemult', '0003_users_stayloggedin_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='recovery_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('recovery_code', models.IntegerField()),
                ('expire', models.IntegerField()),
            ],
        ),
    ]
