# Generated by Django 5.1.4 on 2025-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoemult', '0004_recovery_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
