# Generated by Django 5.1.4 on 2025-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoemult', '0005_users_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='banner_color',
            field=models.CharField(default='#969696', max_length=32),
        ),
    ]
